// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSYDf2bT1vpxpcYSstWAvVtp-b-OpuWi0',
    appId: '1:427747180464:web:398cb1a782339532972075',
    messagingSenderId: '427747180464',
    projectId: 'votingapp-32325',
    authDomain: 'votingapp-32325.firebaseapp.com',
    storageBucket: 'votingapp-32325.appspot.com',
    measurementId: 'G-3MR3N27NCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc2grI6bqVeitFucZsRSMVUvKR1__v3vs',
    appId: '1:427747180464:android:6bca842be95adbcb972075',
    messagingSenderId: '427747180464',
    projectId: 'votingapp-32325',
    storageBucket: 'votingapp-32325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr3EPrdaJUaxbkq-jRNVjcl7YBfLc5qiU',
    appId: '1:427747180464:ios:2cfa03e444290bbb972075',
    messagingSenderId: '427747180464',
    projectId: 'votingapp-32325',
    storageBucket: 'votingapp-32325.appspot.com',
    iosBundleId: 'com.olokart.votingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr3EPrdaJUaxbkq-jRNVjcl7YBfLc5qiU',
    appId: '1:427747180464:ios:2cfa03e444290bbb972075',
    messagingSenderId: '427747180464',
    projectId: 'votingapp-32325',
    storageBucket: 'votingapp-32325.appspot.com',
    iosBundleId: 'com.olokart.votingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSYDf2bT1vpxpcYSstWAvVtp-b-OpuWi0',
    appId: '1:427747180464:web:61da8258d8ded1ee972075',
    messagingSenderId: '427747180464',
    projectId: 'votingapp-32325',
    authDomain: 'votingapp-32325.firebaseapp.com',
    storageBucket: 'votingapp-32325.appspot.com',
    measurementId: 'G-GQBWLS9SVX',
  );

}